import type { Metadata } from "next";
import { Geist, Geist_Mono, Shrikhand } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const display = Shrikhand({
  weight: "400",
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${display.variable} antialiased`}>
        <header className="border-b bg-[var(--background)]">
          <div className="mx-auto max-w-7xl px-6 h-20 flex items-center justify-between">
            <div className="flex items-center gap-6">
              <nav className="hidden md:flex items-center gap-10 text-base font-extrabold tracking-wide">
                <a href="/" className="hover:underline">SHOP</a>
                <a href="/about" className="hover:underline">ABOUT</a>
                <a href="/visit" className="hover:underline">VISIT</a>
              </nav>
            </div>
            <div className="flex items-center gap-4">
              <a href="/seller" className="btn-pop text-xs px-4 py-2">BECOME A SELLER</a>
              <a href="/cart" className="icon-btn" aria-label="Cart">
                <img src="/icons/cart.svg" alt="Cart" width={20} height={20} />
              </a>
              <a href="#" className="icon-btn" aria-label="Account">
                <img src="/icons/user.svg" alt="Account" width={20} height={20} />
              </a>
            </div>
          </div>
        </header>
        <div>{children}</div>
        <footer className="mt-16 border-t">
          <div className="mx-auto max-w-7xl px-6 py-8 text-sm text-gray-600">
            <div className="flex items-center justify-between">
              <span>© {new Date().getFullYear()} Pop Local inspired demo.</span>
              <div className="flex items-center gap-4">
                <a href="#" aria-label="Instagram" className="hover:underline">Instagram</a>
                <a href="#" aria-label="Facebook" className="hover:underline">Facebook</a>
                <a href="#" aria-label="TikTok" className="hover:underline">TikTok</a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
