import type { Metadata } from "next";
import { Geist, Geist_Mono, Shrikhand } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const display = Shrikhand({
  weight: "400",
  variable: "--font-display",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${display.variable} antialiased`}>
        <header className="border-b bg-[var(--background)]">
          <div className="mx-auto max-w-7xl px-6 h-16 flex items-center justify-between">
            <a href="/" className="font-extrabold text-xl">POP</a>
            <nav className="flex items-center gap-4 text-sm">
              <a href="/" className="hover:underline">Shop</a>
              <a href="#gift-boxes" className="hover:underline">Gift Boxes</a>
              <a href="#best-sellers" className="hover:underline">Best Sellers</a>
              <a href="#unique-gifts" className="hover:underline">Unique Gifts</a>
              <a href="#snacky" className="hover:underline">Feeling Snacky?</a>
              <a href="/cart" className="btn-pop text-xs px-3 py-1">Cart</a>
            </nav>
          </div>
        </header>
        <div>{children}</div>
        <footer className="mt-16 border-t">
          <div className="mx-auto max-w-7xl px-6 py-8 text-sm text-gray-600">
            <div className="flex items-center justify-between">
              <span>© {new Date().getFullYear()} Pop Local inspired demo.</span>
              <div className="flex items-center gap-4">
                <a href="#" aria-label="Instagram" className="hover:underline">Instagram</a>
                <a href="#" aria-label="Facebook" className="hover:underline">Facebook</a>
                <a href="#" aria-label="TikTok" className="hover:underline">TikTok</a>
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
