# Generated by Django 5.2.6 on 2026-01-23 02:11

from decimal import Decimal
from django.db import migrations, models


def fix_null_amounts(apps, schema_editor):
    """Fix any existing carts with null amount values"""
    ShoppingCart = apps.get_model('cart', 'ShoppingCart')
    ShoppingCart.objects.filter(amount__isnull=True).update(amount=Decimal('0.00'))


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        # First, fix any existing null values
        migrations.RunPython(fix_null_amounts, migrations.RunPython.noop),
        # Then, update the field definition with default
        migrations.AlterField(
            model_name='shoppingcart',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total price to pay', max_digits=10),
        ),
    ]
