# Generated by Django 5.2.6 on 2026-01-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='great_gift',
            field=models.BooleanField(default=False),
        ),
    ]
