# Generated by Django 5.2.6 on 2026-01-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_great_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='imageUrl',
            field=models.URLField(default='', max_length=500),
        ),
    ]
