# Generated by Django 5.2.6 on 2026-01-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_href_category_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='great_gift',
        ),
    ]
