# Generated by Django 5.2.6 on 2026-01-17 02:34
# Modified: Category dependency removed since category app is deleted
# Fixed: Removed SeparateDatabaseAndState to actually create the products table

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Category dependency removed since category app is deleted
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(help_text='Company or producer/artist that makes the product', max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in .xx format', max_digits=10)),
                ('profile_pic_link', models.URLField(max_length=500)),
                ('detail_pic_links', models.JSONField(blank=True, default=list, help_text='Array of image URLs', null=True)),
                ('tag', models.CharField(blank=True, choices=[('new', 'New'), ('hot', 'Hot')], max_length=10, null=True)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
