# Generated by Django 5.2.6 on 2026-01-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=False)),
                ('new_if', models.FloatField(default=0.0)),
                ('hot', models.BooleanField(default=False)),
                ('hot_if', models.FloatField(default=0.0)),
                ('rank_if', models.FloatField(default=0.0)),
                ('gift_box', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='product.product')),
            ],
            options={
                'db_table': 'product_tags',
            },
        ),
    ]
