# Generated by Django 5.2.6 on 2026-01-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_tag_producttag'),
    ]

    operations = [
        # Rename company field to brand
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='brand',
        ),
        # Add type field with default empty list
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.JSONField(default=list, help_text="Array of product types (e.g., ['Gift Box', 'Limited Edition'])"),
        ),
        # Remove gift_box field from ProductTag
        migrations.RemoveField(
            model_name='producttag',
            name='gift_box',
        ),
    ]
