# Generated by Django 5.2.6 on 2026-01-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_company_to_brand_and_add_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(help_text='Brand or producer/artist that makes the product', max_length=200),
        ),
    ]
