# Generated by Django 5.2.6 on 2026-01-18 23:10

import django.db.models.deletion
from django.db import migrations, models


def create_brands_and_migrate_data(apps, schema_editor):
    """Create Brand objects from existing Product brand strings and insert new brands"""
    Brand = apps.get_model('product', 'Brand')
    Product = apps.get_model('product', 'Product')
    
    # Get all unique brand names from existing products
    existing_brands = Product.objects.values_list('brand', flat=True).distinct()
    
    # Create Brand objects for existing brands with default descriptions
    brand_map = {}
    for brand_name in existing_brands:
        if brand_name:  # Skip empty strings
            brand, created = Brand.objects.get_or_create(
                name=brand_name,
                defaults={
                    'description': f'{brand_name} is a trusted brand offering quality products that reflect their commitment to excellence and customer satisfaction.'
                }
            )
            brand_map[brand_name] = brand
    
    # Insert the new brands provided by the user (deduplicated)
    new_brands_data = [
        "Contentious Character Winery",
        "Poncho Fox Distillery",
        "Ambrosia Distillery",
        "Fruity Stones",
        "Dangly Bits",
        "Lucian Candles",
        "Zealous & Co",
        "Altina",
        "Tilda Joy",
        "Josies Crochet",
        "Local Spirit Group",
        "Riverbourne Distillery Pty Ltd",
        "Kate's Bombs",
        "POP Local",
        "Julia Ockert Art",
        "The Prime Ginister",
    ]
    
    # Descriptions for each brand (approximately 50 words each)
    brand_descriptions = {
        "Contentious Character Winery": "Contentious Character Winery is a boutique winery known for producing exceptional wines with character and depth. Their commitment to quality and unique flavor profiles has made them a favorite among wine enthusiasts. Each bottle tells a story of passion, craftsmanship, and the perfect balance between tradition and innovation in winemaking.",
        "Poncho Fox Distillery": "Poncho Fox Distillery crafts premium spirits with a focus on quality and innovation. Their artisanal approach to distillation results in unique flavors that capture the essence of their craft. Known for their attention to detail and commitment to excellence, Poncho Fox creates spirits that are both sophisticated and approachable for discerning drinkers.",
        "Ambrosia Distillery": "Ambrosia Distillery specializes in creating refined spirits that embody elegance and sophistication. Their dedication to traditional distillation methods combined with modern techniques produces exceptional beverages. Each product reflects their passion for quality and their commitment to providing customers with memorable drinking experiences that celebrate craftsmanship.",
        "Fruity Stones": "Fruity Stones offers vibrant and playful products that bring joy and color to everyday life. Their unique designs and quality craftsmanship make them a beloved brand among customers seeking fun and functional items. With a focus on creativity and innovation, Fruity Stones creates products that stand out and bring smiles to faces.",
        "Dangly Bits": "Dangly Bits creates distinctive accessories and decorative items that add personality and charm to any space. Their unique designs and attention to detail make them a favorite among those who appreciate quirky and creative home decor. Each piece is crafted with care to bring character and style to your surroundings.",
        "Lucian Candles": "Lucian Candles crafts premium candles that transform any space into a sanctuary of warmth and ambiance. Their carefully curated scents and high-quality wax formulations create long-lasting, beautiful candles. With a focus on sustainability and craftsmanship, Lucian Candles offers products that enhance your home environment and create memorable moments.",
        "Zealous & Co": "Zealous & Co is a brand dedicated to creating products that inspire passion and enthusiasm. Their commitment to quality and innovative design results in items that customers love and trust. With a focus on excellence and customer satisfaction, Zealous & Co delivers products that make a positive impact on daily life.",
        "Altina": "Altina represents elegance and sophistication in every product they create. Their commitment to quality craftsmanship and timeless design makes them a trusted brand for discerning customers. Each item reflects their dedication to excellence and their passion for creating products that stand the test of time.",
        "Tilda Joy": "Tilda Joy brings happiness and delight through their thoughtfully designed products. Their commitment to quality and cheerful aesthetics makes them a beloved brand among customers. With a focus on creating items that spark joy, Tilda Joy offers products that enhance everyday experiences and bring smiles to faces.",
        "Josies Crochet": "Josies Crochet creates beautiful handcrafted items that showcase the art of crochet. Their attention to detail and commitment to traditional craftsmanship results in unique, high-quality products. Each piece reflects the passion and skill of the artisan, offering customers one-of-a-kind items that celebrate the beauty of handmade goods.",
        "Local Spirit Group": "Local Spirit Group is dedicated to supporting local producers and creating exceptional spirits that celebrate regional flavors. Their commitment to community and quality results in products that tell the story of their origins. With a focus on sustainability and local partnerships, they create spirits that are both delicious and meaningful.",
        "Riverbourne Distillery Pty Ltd": "Riverbourne Distillery Pty Ltd produces premium spirits with a focus on quality and regional character. Their dedication to traditional distillation methods and local ingredients creates unique flavors that reflect their heritage. Each product represents their commitment to excellence and their passion for creating exceptional spirits.",
        "Kate's Bombs": "Kate's Bombs offers innovative and exciting products that make a statement. Their unique approach to design and quality results in items that stand out and capture attention. With a focus on creativity and excellence, Kate's Bombs creates products that are both functional and fun, bringing excitement to everyday life.",
        "POP Local": "POP Local is a community-focused brand that celebrates local culture and craftsmanship. Their commitment to supporting local makers and creating quality products makes them a trusted name in the community. With a focus on authenticity and connection, POP Local offers products that reflect the spirit and character of the local area.",
        "Julia Ockert Art": "Julia Ockert Art creates beautiful artistic products that celebrate creativity and self-expression. Their unique designs and commitment to quality craftsmanship result in items that are both functional and inspiring. Each piece reflects the artist's passion and vision, offering customers products that bring art into everyday life.",
        "The Prime Ginister": "The Prime Ginister specializes in crafting exceptional gin with a focus on quality and unique botanical blends. Their dedication to the art of distillation results in spirits that are both sophisticated and approachable. Each bottle represents their commitment to excellence and their passion for creating memorable drinking experiences.",
    }
    
    # Create Brand objects for new brands
    for brand_name in new_brands_data:
        if brand_name not in brand_map:  # Only create if it doesn't already exist
            brand = Brand.objects.create(
                name=brand_name,
                description=brand_descriptions.get(brand_name, f'{brand_name} is a trusted brand offering quality products that reflect their commitment to excellence and customer satisfaction.')
            )
            brand_map[brand_name] = brand
    
    # Update all products to reference the Brand objects via brand_id
    for product in Product.objects.all():
        if product.brand and product.brand in brand_map:
            # Update the brand_id field directly
            Product.objects.filter(id=product.id).update(brand_id=brand_map[product.brand].id)
        else:
            # Create a default brand for products with empty or missing brands
            default_brand, _ = Brand.objects.get_or_create(
                name='Unknown Brand',
                defaults={
                    'description': 'A brand for products without a specified brand name.'
                }
            )
            Product.objects.filter(id=product.id).update(brand_id=default_brand.id)


def reverse_migration(apps, schema_editor):
    """Reverse migration - not fully implemented as we lose original brand strings"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand'),
    ]

    operations = [
        # Step 1: Create Brand model
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Brand description')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        # Step 2: Add temporary brand_id field to Product
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.IntegerField(null=True, blank=True),
        ),
        # Step 3: Migrate data (create brands and populate brand_id)
        migrations.RunPython(create_brands_and_migrate_data, reverse_migration),
        # Step 4: Remove old brand CharField
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        # Step 5: Rename brand_id to brand
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        # Step 6: Convert brand to ForeignKey
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(help_text='Brand or producer/artist that makes the product', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.brand'),
        ),
    ]
