# Generated by Django 5.2.6 on 2026-01-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_brand_delete_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_pic_links',
            field=models.JSONField(blank=True, default=list, help_text="Array of image objects, each containing 'small' (thumbnail) and 'big' (large) image URLs. Format: [{'small': 'url_100x100', 'big': 'url_700x780'}, ...]", null=True),
        ),
    ]
