# Generated by Django 5.2.6 on 2026-01-19 06:13

import re
from django.db import migrations, models


def copy_detail_pic_links_to_backup(apps, schema_editor):
    """Copy detail_pic_links to backup field before removing it"""
    Product = apps.get_model('product', 'Product')
    for product in Product.objects.all():
        if hasattr(product, 'detail_pic_links') and product.detail_pic_links:
            product.detail_pic_links_backup = product.detail_pic_links
            product.save(update_fields=['detail_pic_links_backup'])


def migrate_detail_pic_links_to_detail_pics(apps, schema_editor):
    """Migrate existing detail_pic_links JSONField data to ProductDetailPic model"""
    Product = apps.get_model('product', 'Product')
    ProductDetailPic = apps.get_model('product', 'ProductDetailPic')
    
    for product in Product.objects.all():
        # Access the backup field
        detail_pic_links_backup = getattr(product, 'detail_pic_links_backup', None)
        if detail_pic_links_backup:
            detail_pics = []
            for pic_url in detail_pic_links_backup:
                if pic_url and isinstance(pic_url, str):  # Skip empty URLs
                    # Create ProductDetailPic with all three sizes
                    # Convert URL pattern: replace 100x100 with larger sizes
                    small_url = pic_url
                    big_url = re.sub(r'100x100', '700x780', pic_url)
                    extra_big_url = re.sub(r'100x100', '1500x1500', pic_url)
                    
                    detail_pic, _ = ProductDetailPic.objects.get_or_create(
                        small_pic_link=small_url,
                        defaults={
                            'big_pic_link': big_url,
                            'extra_big_pic_link': extra_big_url,
                        }
                    )
                    detail_pics.append(detail_pic)
            
            # Assign the detail pics to the product
            if detail_pics:
                product.detail_pics.set(detail_pics)


def reverse_migration(apps, schema_editor):
    """Reverse migration - convert ProductDetailPic back to detail_pic_links"""
    Product = apps.get_model('product', 'Product')
    
    for product in Product.objects.all():
        if product.detail_pics.exists():
            # Convert detail_pics back to array of small URLs
            pic_urls = list(product.detail_pics.values_list('small_pic_link', flat=True))
            product.detail_pic_links_backup = pic_urls
            product.save(update_fields=['detail_pic_links_backup'])


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_update_detail_pic_links_structure'),
    ]

    operations = [
        # Step 1: Create ProductDetailPic model
        migrations.CreateModel(
            name='ProductDetailPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_pic_link', models.URLField(help_text='Small thumbnail image URL (e.g., 100x100)', max_length=500)),
                ('big_pic_link', models.URLField(help_text='Large image URL (e.g., 700x780)', max_length=500)),
                ('extra_big_pic_link', models.URLField(help_text='Extra large image URL for modal/zoom view', max_length=500)),
            ],
            options={
                'db_table': 'product_detail_pics',
                'ordering': ['id'],
            },
        ),
        # Step 2: Add temporary detail_pic_links_backup field to preserve data
        migrations.AddField(
            model_name='product',
            name='detail_pic_links_backup',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        # Step 3: Copy detail_pic_links to backup
        migrations.RunPython(copy_detail_pic_links_to_backup, reverse_migration),
        # Step 4: Remove old detail_pic_links field
        migrations.RemoveField(
            model_name='product',
            name='detail_pic_links',
        ),
        # Step 5: Add new detail_pics ManyToMany field
        migrations.AddField(
            model_name='product',
            name='detail_pics',
            field=models.ManyToManyField(blank=True, help_text='Array of product detail picture IDs', related_name='products', to='product.productdetailpic'),
        ),
        # Step 6: Migrate data from backup to ProductDetailPic
        migrations.RunPython(migrate_detail_pic_links_to_detail_pics, reverse_migration),
        # Step 7: Remove backup field
        migrations.RemoveField(
            model_name='product',
            name='detail_pic_links_backup',
        ),
    ]
