# Generated by Django 5.2.6 on 2026-01-20 02:22
# Modified: Handle case where category field may not exist in migration state

from django.db import migrations


def remove_category_field_if_exists(apps, schema_editor):
    """Remove category field from database if it exists"""
    Product = apps.get_model('product', 'Product')
    # Check if column exists and remove it
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='products' AND column_name='category_id'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE products DROP COLUMN IF EXISTS category_id CASCADE;")


def reverse_remove_category_field(apps, schema_editor):
    """Reverse operation - we don't recreate the category field since category app is deleted"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_productdetailpic_remove_product_detail_pic_links_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_category_field_if_exists,
            reverse_remove_category_field,
        ),
    ]
