# Generated by Django 5.2.6 on 2026-01-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Brand',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Brand name', max_length=200, unique=True)),
                        ('description', models.TextField(help_text='Brand description')),
                    ],
                    options={
                        'db_table': 'brands',
                        'ordering': ['name'],
                    },
                ),
            ],
        ),
    ]
